Application:
    Port: 8080
    ContextPath: /api
Authorization:
    TokenExpiration: 3600
    AuthorizationHeader: Authorization
    AuthorizationType: cookies
    TokenEncodingType: jwt
    JWT:
        TokenEncoding: Wow, much safe
    ExcludedPaths:
        - /api/user/register
        - /api/user/login
    Encryption:
        Cost: 10
Cache:
    Name: redis
    URL: localhost:6379
    Expiration: 300
Database:
    Name: sqlite
    URL: ./custom.db
