Application:
    Port: 8080
    ContextPath: /api
Authorization:
    TokenExpiration: 3600
    AuthorizationHeader: Authorization
    AuthorizationType: jwt
    TokenEncodingType: jwt
    JWT:
        TokenEncoding: Wow, much safe
    ExcludedPaths:
        - /api/user/register
        - /api/user/login
Cache:
    URL: localhost:6379
    Expiration: 300
