version: '3.5'

services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: Password
    networks:
      user-authorizaton:
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      user-authorizaton:
  memcache:
    image: memcached
    ports:
      - "11211:11211"
    networks:
      user-authorizaton:
networks:
  user-authorizaton: